language: java
jdk:
- openjdk8
script: mvn clean verify

deploy:
  provider: heroku
  api_key:
  secure: Pgr1I4yRCoN4tsm9mxKAdVg3tioA6b/W6dS9vzBEeLEeR/altWqXZW8Fx6cnkIyN2Dma8eB81z3t4tc6Wch1bhVsYb0LqX6SP+cQTQtcRJWUqx8zTkR9ffcJxUa3sKd5GOKism3Q3SJDBJl1kQxqq29Ne/JojwTZyb3gYJ9YI/MoNXlc0JR8SPD2me8YFuCSD9PnISYBfgBFzkohqpu5k8ylwx3kBxEhWWPAhJWUZzUHpVrWjNcKnMU48aXxRZrbClSChYCTsOXZunzNpNqvTSv29yHZFXScZC4o3EJm2td/PQQOmIWwYNmXvsnW9tSN6DDms/tqRcVLERgDDN9B1ey+kUkjnJG6bgXlhel7uxOpQrSFbatUdB0KCxWLb3rjkP32sDd47jyLdRWN++e97gMyktlCKnfn7YvkIPlOKhz/wEcFQ+y1ZsBo45l4yoAOzq8F7zesev8rT/cnYLURXJ73mmMfaRj3pI8Oe1+RIWwnC5tcZNWFJqiPQJfFYonn/vsmlqdoPGu7WnIaya7ymVLVtREzBqSVM9TOgXB2rw4d3jHQHzVTWm6OcOQ+5rgL+C1MH7/7jt/pl8A6GULmdrdZZ0Lmg3ul9wK+QrOFCBvzSe8XCQ09emtBLHMXpoD0BRcWOwrCNYY6jTq4qL32Dx6v5g+Tbj6sxhci2DkNqWs=
  app: horse-battery-spiedagnel
